### ISSUE TITLE
[Bug]: Homepage UI can be made responsive for all devices [Majorly mobile] and a detailed instructions can be added

### ISSUE THREAD

**Issue by srinidhifd** [ChromeGaming/Dot-Box#356]
### Give a brief about the bug ✍️

The home page UI is not responsive on mobile phones. 
Instructions are unclear and less for beginners to play the game.
![iphone-before](https://github.com/ChromeGaming/Dot-Box/assets/93462562/69b10c5f-c53d-4c36-8877-8fc8ddac587a)
![iphone-mini-before](https://github.com/ChromeGaming/Dot-Box/assets/93462562/41a53391-d744-4802-afd9-4727c8d3354c)
![op-nord-2-before](https://github.com/ChromeGaming/Dot-Box/assets/93462562/96e2232b-cae6-46c6-9f17-2d06ef78f200)
![xiaomi-12-before](https://github.com/ChromeGaming/Dot-Box/assets/93462562/7ef0f088-6c31-4ce8-be14-7a969d721411)

### What is the expected behavior? 🤔

Home page Can be made responsive for all devices [Majorly for Mobile Phones]The home

### Provide step by step information reproduce the bug 📄

Responsiveness can be made using media queries or using bootstrap
A detailed instructions/rules page can be added separately or on the homepage itself, depending on Project admin instructions.

@Durgesh4993 @ayush-t02  Please assign this issue to me under GSSOC'24 with respective Level  label.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kharedevansh11** [comment]
Hi @Durgesh4993 and @ayush-t02,

I have made a fix for the issue raised regarding the responsiveness of the home page. Here are the steps I followed to resolve it:

**Implemented Media Queries**: Added media queries to ensure the home page is responsive across different devices, especially mobile phones.

**Enhanced Layout:** Adjusted the layout elements to ensure a user-friendly experience on smaller screens.

### **Expected Behavior:**
The home page is now responsive across all devices, providing an optimal viewing experience on mobile phones.

### **Reproduction Steps:**

Open the home page on a mobile device or resize the browser window to a smaller width.

Observe that the layout adjusts gracefully, ensuring all elements are accessible and readable.

### **Next Steps:**

Please assign this issue to me under GSSOC'24 with the respective Level label so I can push my changes and open a pull request for review.

### **Program:**

GSSOC'24

**Code of Conduct:**

- [x]  I follow the _CONTRIBUTING GUIDELINES_ of this project.


Thank you!
<img width="1680" alt="Screenshot 2024-06-15 at 4 31 21 PM" src="https://github.com/ChromeGaming/Dot-Box/assets/114429259/4b648059-3245-4eb4-9a39-5f6d5f2108cc">
<img width="1680" alt="Screenshot 2024-06-15 at 4 31 35 PM" src="https://github.com/ChromeGaming/Dot-Box/assets/114429259/453b068d-28ec-4ffc-b7bd-c5f927766be6">

**Comment by kharedevansh11** [comment]
I have made it fully responsive for all screen sizes using best coding practices.
